# Generated by Django 5.2.9 on 2026-01-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datostecnicoscliente',
            name='url_portal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
