# Generated by Django 5.2.9 on 2026-01-11 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_datostecnicoscliente_url_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(choices=[('EMAIL', 'Envío de Correo'), ('SYNC', 'Sincronización Facturas')], max_length=10)),
                ('estado', models.CharField(choices=[('EXITO', 'Exitoso'), ('ERROR', 'Fallido'), ('ADVERTENCIA', 'Advertencia')], max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción breve de la acción')),
                ('detalle_error', models.TextField(blank=True, help_text='Traza completa del error técnico', null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.datosgeneralescliente')),
            ],
        ),
    ]
