# Generated by Django 5.2.9 on 2026-01-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_bitacoraeventos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitacoraEventos',
        ),
    ]
