# Generated by Django 5.2.10 on 2026-04-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_delete_bitacoraeventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosservicio',
            name='mod_ventas',
            field=models.BooleanField(default=True, verbose_name='Ventas (Facturación)'),
        ),
        migrations.AlterField(
            model_name='datosservicio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosservicio',
            name='precio_pactado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datostecnicoscliente',
            name='nombre_basedatos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datostecnicoscliente',
            name='servidor_alojamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.servidorbasedatos'),
        ),
    ]
