# Generated by Django 5.2.10 on 2026-04-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_datosservicio_mod_ventas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosservicio',
            name='fecha_caducidad_firma',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Caducidad Firma'),
        ),
        migrations.AlterField(
            model_name='datosservicio',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='datosservicio',
            name='fecha_renovacion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datosservicio',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
