# Generated by Django 5.2.10 on 2026-05-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_datosservicio_fecha_caducidad_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosservicio',
            name='alerta_vencimiento_enviada',
            field=models.BooleanField(default=False, help_text='Se marca al enviar aviso de 15 días del vencimiento'),
        ),
    ]
